"""add author and date

Revision ID: 6b5a1b6589af
Revises: b711585c1504
Create Date: 2026-04-27 15:07:15.235799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5a1b6589af'
down_revision = 'b711585c1504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rbfb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(64), nullable=False, server_default='Griffin'))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False, server_default='2026-04-27'))
        batch_op.create_index(batch_op.f('ix_rbfb_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_rbfb_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rbfb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rbfb_date'))
        batch_op.drop_index(batch_op.f('ix_rbfb_author'))
        batch_op.drop_column('date')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
