"""url val

Revision ID: 8199b98c3561
Revises: fc20862700ed
Create Date: 2025-12-18 09:19:29.778459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8199b98c3561'
down_revision = 'fc20862700ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rbfb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urlval', sa.String(length=8)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rbfb', schema=None) as batch_op:
        batch_op.drop_column('urlval')

    # ### end Alembic commands ###
