"""Initial tables

Revision ID: a5c5cef75cb1
Revises: 
Create Date: 2025-12-17 15:28:31.301757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c5cef75cb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rbfb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rbfb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rbfb_topic'), ['topic'], unique=False)

    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('real', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['rbfb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    with op.batch_alter_table('rbfb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rbfb_topic'))

    op.drop_table('rbfb')
    # ### end Alembic commands ###
