"""added hue to RBFB

Revision ID: b711585c1504
Revises: 8199b98c3561
Create Date: 2026-01-05 15:41:20.309147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b711585c1504'
down_revision = '8199b98c3561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_rbfb')
    with op.batch_alter_table('rbfb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hue', sa.Integer(), nullable=True))
        batch_op.alter_column('urlval',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rbfb', schema=None) as batch_op:
        batch_op.alter_column('urlval',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.drop_column('hue')

    op.create_table('_alembic_tmp_rbfb',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=64), nullable=False),
    sa.Column('urlval', sa.VARCHAR(length=8), nullable=False),
    sa.Column('hue', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
