"""table changes

Revision ID: fc20862700ed
Revises: a5c5cef75cb1
Create Date: 2025-12-17 15:52:13.570846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc20862700ed'
down_revision = 'a5c5cef75cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('real', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['rbfb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('entry')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.VARCHAR(length=64), nullable=False),
    sa.Column('real', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['rbfb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('candidate')
    # ### end Alembic commands ###
